name: lavapp
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.6.0
  fl_chart: ^0.70.2  
  firebase_core: ^3.12.1
  http: ^1.2.2
  path: ^1.8.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  url_launcher: ^6.1.8
  intl: ^0.20.2
  shared_preferences: ^2.2.3
  logger: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1  
  lints: ^5.1.1  # Cambiado de ^6.0.0 a ^5.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/app_icon.png"